// apps/web/src/routes/s/sites/+page.svelte
<script lang="ts">
	import { api } from '$lib/convex';
	import DataTable from '$lib/components/table/DataTable.svelte';
	import { type DataTableCell } from '$lib/components/table/types.js';
	import Button from '$lib/components/ui/button/button.svelte';
	import { getAppState } from '$lib/state/Application.svelte.js';
	import { prettyText } from '@workspace/shared/lib/utils.js';

	const appState = getAppState();
</script>

<div class="flex size-full flex-col gap-4 overflow-hidden">
	<h1 class="shrink-0 text-2xl">Sites</h1>

	{#snippet cellSnip({ row }: DataTableCell<SiteWithDetails>)}
		<Button
			href={`/s/sites/${row.slug}`}
			variant="link"
			class="p-0 text-primary-foreground hover:text-primary hover:no-underline"
			onclick={() => appState.setSite(row as any)}
		>
			{row.name}
		</Button>
	{/snippet}

	<DataTable
		fetcher={async (state) => {
			const result = await appState.convex.query(api.sites.crud.list, {
				page: state.page ?? 0,
				pageSize: state.size ?? 100,
				search: state.globalSearch,
				sorting: state.sorting || { name: 'asc' }
			});

			return result;
		}}
		columns={[
			{
				key: 'name',
				title: 'Name',
				searchable: true,
				sortable: true,
				cell: cellSnip
			},
			{
				key: 'psaIntegrationName',
				title: 'PSA',
				searchable: false,
				sortable: false,
				render: ({ row }) => prettyText(row.psaIntegrationName)
			},
			{
				key: 'psaCompanyId',
				title: 'PSA ID',
				hideable: true,
				sortable: true
			}
		]}
	/>
</div>

// web/src/app/(secure)/sites/page.tsx
"use client";

import { DataTable } from "@/components/DataTable/DataTable";
import fetchTableData from "@/lib/supabase/table-fetcher";
import { DataTableColumn, DataTableFetchParams } from "@/lib/types/datatable";
import { Badge } from "@/components/ui/badge";
import { prettyText } from "@workspace/shared/lib/utils";
import { Tables } from "@workspace/shared/types/database";
import Link from "next/link";

type Data = Tables<"sites_view">;

const columns: DataTableColumn<Data>[] = [
  {
    key: "name",
    label: "Name",
    sortable: true,
    filterable: true,
    searchable: true,
    render: (value, row) => (
      <Link
        href={`/sites/${row.slug}`}
        className="font-medium hover:text-primary"
      >
        {value}
      </Link>
    ),
  },
  {
    key: "parent_name",
    label: "Parent",
    sortable: true,
    filterable: true,
    searchable: true,
    render: (value, row) => (
      <Link
        href={`/sites/${row.parent_slug}`}
        className="font-medium hover:text-primary"
      >
        {value}
      </Link>
    ),
  },
  {
    key: "status",
    label: "Status",
    sortable: true,
    filterable: true,
    filterType: "select",
    filterOptions: [
      { label: "Active", value: "active" },
      { label: "Inactive", value: "inactive" },
    ],
    render: (value) => (
      <Badge variant={value === "active" ? "default" : "secondary"}>
        {prettyText(value as string)}
      </Badge>
    ),
  },
];

export default function Page() {
  const fetcher = async (params: DataTableFetchParams) => {
    return await fetchTableData<Data>("sites_view", params);
  };

  return (
    <div className="grid gap-2 p-4">
      <div>
        <h1 className="text-2xl font-semibold">Sites</h1>
      </div>
      <DataTable
        columns={columns}
        fetcher={fetcher}
        initialSort={[{ column: "name", direction: "asc" }]}
        enableRefresh={true}
        enableExport={true}
        enableColumnToggle={true}
        useUrlState={true}
        urlStateKey="sites"
      />
    </div>
  );
}
