// packages/ui/src/components/SubmitButton.tsx
"use client";

import { Button } from "@workspace/ui/components/button";
import { Spinner } from "@workspace/ui/components/Spinner";
import { type ComponentProps } from "react";
import { useFormStatus } from "react-dom";

type Props = ComponentProps<typeof Button> & {
  pending?: boolean;
};

export function SubmitButton({ children, disabled, pending, ...props }: Props) {
  const { pending: status } = useFormStatus();

  const isDisabled = disabled || status || pending;

  return (
    <Button
      type="submit"
      aria-disabled={isDisabled}
      disabled={isDisabled}
      {...props}
    >
      {(status || pending) && <Spinner size={18} />} {children}
    </Button>
  );
}

// apps/web/src/lib/components/SubmitButton.svelte
<script lang="ts">
	import Loader from '$lib/components/Loader.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import type { ComponentProps } from 'svelte';

	type Props = {
		isLoading?: boolean;
	} & ComponentProps<typeof Button>;

	const { isLoading, type = 'submit', children, disabled, ...rest }: Props = $props();
</script>

<Button {type} {...rest} disabled={isLoading || disabled}>
	{#if isLoading}
		<Loader size="sm" />
	{/if}
	{#if children}
		{@render children()}
	{/if}
</Button>
