// apps/web/src/routes/(private)/integrations/+page.svelte
<script lang="ts">
	import SearchBar from '$lib/components/SearchBar.svelte';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import Button from '$lib/components/ui/button/button.svelte';
	import * as Card from '$lib/components/ui/card/index.js';
	import { api } from '$lib/convex/index.js';
	import { useQuery } from 'convex-svelte';
	import { Search, Settings } from 'lucide-svelte';

	let search = $state('');
	let tags: string[] = $state([]);

	const query = useQuery(api.integrations.query.listActiveWithDataSource, {});
	const integrations = $derived(query.data);

	// Computed: filtered integrations based on search and tags
	const filteredIntegrations = $derived.by(() => {
		if (!integrations) return [];

		const term = search.toLowerCase();

		return integrations.filter((integ) => {
			const lowerName = integ.name?.toLowerCase() ?? '';
			const lowerDesc = integ.description?.toLowerCase() ?? '';

			const matchesSearch = lowerName.includes(term) || lowerDesc.includes(term);
			const matchesTags = tags.length === 0 || tags.includes(integ.category);

			return matchesSearch && matchesTags;
		});
	});

	// Computed: unique category tags from all integrations
	const uniqueTags = $derived.by(() => {
		if (!integrations) return [];

		const tagSet = new Set<string>();
		for (const integ of integrations) {
			if (integ.category) {
				tagSet.add(integ.category);
			}
		}

		return Array.from(tagSet);
	});
</script>

<div class="flex size-full flex-col gap-4">
	<h1 class="text-2xl">Integrations</h1>

	<!--Header-->
	<div>
		<SearchBar
			placeholder="Search Integrations"
			onSearch={(val) => (search = val)}
			icon={Search}
			class="w-1/3"
			delay={0}
		/>
		<!--Tags-->
		<div class="flex gap-1 py-1">
			{#each uniqueTags as tag}
				<Badge
					onclick={() => {
						if (tags.includes(tag)) tags = tags.filter((t) => t !== tag);
						else tags.push(tag);
					}}
					variant={tags.includes(tag) ? 'default' : 'outline'}
					class="text-sm hover:cursor-pointer hover:bg-secondary"
				>
					{tag}
				</Badge>
			{/each}
		</div>
	</div>

	<!--Integrations Grid-->
	{#if query.isLoading}
		<!-- Loading state -->
		<div class="grid grid-cols-4 gap-2">
			{#each Array(8) as _}
				<Card.Root class="animate-pulse justify-between">
					<Card.Header>
						<div class="h-6 w-3/4 rounded bg-muted"></div>
						<div class="mt-2 h-4 w-full rounded bg-muted"></div>
					</Card.Header>
					<Card.Content>
						<div class="h-6 w-1/2 rounded bg-muted"></div>
					</Card.Content>
				</Card.Root>
			{/each}
		</div>
	{:else if filteredIntegrations.length === 0}
		<!-- Empty state -->
		<div class="flex h-64 items-center justify-center">
			<p class="text-muted-foreground">No integrations found</p>
		</div>
	{:else}
		<!-- Integrations list -->
		<div class="grid grid-cols-4 gap-2">
			{#each filteredIntegrations as integ}
				<Card.Root class="justify-between">
					<Card.Header>
						<Card.Title>
							{integ.name}
						</Card.Title>
						<Card.Description>
							{integ.description}
						</Card.Description>
					</Card.Header>
					<Card.Content>
						<div class="flex items-center justify-between">
							<div class="flex gap-1">
								{#if integ.isEnabled && integ.dataSourceStatus === 'active'}
									<Badge>Enabled</Badge>
								{:else if integ.isEnabled}
									<Badge variant="outline">{integ.dataSourceStatus}</Badge>
								{:else}
									<Badge variant="outline">Available</Badge>
								{/if}
								<Badge variant="secondary">{integ.category}</Badge>
							</div>

							<Button class="size-fit !p-2" variant="ghost" href={`/integrations/${integ.slug}`}>
								<Settings class="w-4" />
							</Button>
						</div>
					</Card.Content>
				</Card.Root>
			{/each}
		</div>
	{/if}
</div>

// apps/frontend/app/secure/default/integrations/page.tsx
"use client"

import SearchBar from "@/components/SearchBar";
import { api } from "@/lib/api"
import { prettyText } from "@workspace/shared/lib/utils";
import { Badge } from "@workspace/ui/components/badge";
import Loader from "@workspace/ui/components/Loader";
import { useQuery } from "convex/react"
import { Search } from "lucide-react";
import Link from "next/link";

export default function IntegrationsPage() {
    const integrations = useQuery(api.integrations.query.listActiveWithDataSource);

    return (
        <div className="flex flex-col gap-5 size-full">
            <SearchBar placeholder="Search integrations..." lead={<Search className="w-4" />} className="!bg-input w-1/4 !border-border" />
            {!integrations && <Loader />}
            <div className="grid grid-cols-4 size-full gap-2">
                {integrations?.map((integration) => {
                    return (
                        <div key={integration._id} className="flex flex-col gap-2 bg-card/50 border rounded shadow h-40 p-4">
                            <Link href={`/secure/default/integrations/${integration.slug}`}>{integration.name}</Link>
                            <span className="text-muted-foreground text-sm">{integration.description}</span>

                            <div className="mt-auto flex gap-2">
                                <Badge>{prettyText(integration.dataSourceStatus)}</Badge>
                                <Badge variant="secondary">{prettyText(integration.category)}</Badge>
                            </div>
                        </div>
                    )
                })}
            </div>
        </div>
    )
}
