// web/src/app/(secure)/sites/page.tsx
"use client";

import { DataTable } from "@/components/DataTable/DataTable";
import fetchTableData from "@/lib/supabase/table-fetcher";
import { DataTableColumn, DataTableFetchParams } from "@/lib/types/datatable";
import { Badge } from "@/components/ui/badge";
import { prettyText } from "@workspace/shared/lib/utils";
import { Tables } from "@workspace/shared/types/database";
import Link from "next/link";

type Data = Tables<"sites_view">;

const columns: DataTableColumn<Data>[] = [
  {
    key: "name",
    label: "Name",
    sortable: true,
    filterable: true,
    searchable: true,
    render: (value, row) => (
      <Link
        href={`/sites/${row.slug}`}
        className="font-medium hover:text-primary"
      >
        {value}
      </Link>
    ),
  },
  {
    key: "parent_name",
    label: "Parent",
    sortable: true,
    filterable: true,
    searchable: true,
    render: (value, row) => (
      <Link
        href={`/sites/${row.parent_slug}`}
        className="font-medium hover:text-primary"
      >
        {value}
      </Link>
    ),
  },
  {
    key: "status",
    label: "Status",
    sortable: true,
    filterable: true,
    filterType: "select",
    filterOptions: [
      { label: "Active", value: "active" },
      { label: "Inactive", value: "inactive" },
    ],
    render: (value) => (
      <Badge variant={value === "active" ? "default" : "secondary"}>
        {prettyText(value as string)}
      </Badge>
    ),
  },
];

export default function Page() {
  const fetcher = async (params: DataTableFetchParams) => {
    return await fetchTableData("sites_view", {
      pagination: params,
    });
  };

  return (
    <div className="grid gap-2 p-4">
      <div>
        <h1 className="text-2xl font-semibold">Sites</h1>
      </div>
      <DataTable
        columns={columns}
        fetcher={fetcher}
        initialSort={[{ column: "name", direction: "asc" }]}
        enableRefresh={true}
        enableExport={true}
        enableColumnToggle={true}
        useUrlState={true}
        urlStateKey="sites"
      />
    </div>
  );
}

// apps/web/src/routes/(private)/sites/+page.svelte
<script lang="ts">
	import DataTable from '$lib/components/table/DataTable.svelte';
	import { type DataTableCell } from '$lib/components/table/types.js';
	import Button from '$lib/components/ui/button/button.svelte';
	import { createClient } from '$lib/database/client.js';
	import { ORM } from '$lib/database/orm.js';
	import { getAppState } from '$lib/state/Application.svelte.js';
	import { prettyText } from '$shared/lib/utils.js';
	import { type Tables } from '@workspace/shared/types/database/index.js';

	const appState = getAppState();
</script>

<div class="flex size-full flex-col gap-4 overflow-hidden">
	<h1 class="shrink-0 text-2xl">Sites</h1>

	{#snippet cellSnip({ row }: DataTableCell<Tables<'sites_view'>>)}
		<Button
			href={`/sites/${row.slug}`}
			variant="link"
			class="p-0 text-primary-foreground hover:text-primary hover:no-underline"
			onclick={() => appState.setSite(row)}
		>
			{row.name}
		</Button>
	{/snippet}

	<DataTable
		fetcher={async (state) => {
			const supabase = createClient();
			const orm = new ORM(supabase);

			state.sorting = state.sorting || { name: 'asc' };

			const { data } = await orm.getRows('sites_view', {
				pagination: state
			});

			return (
				data || {
					rows: [],
					total: 0
				}
			);
		}}
		columns={[
			{
				key: 'name',
				title: 'Name',
				searchable: true,
				sortable: true,
				cell: cellSnip
			},
			{
				key: 'parent_name',
				title: 'Parent',
				searchable: true,
				sortable: true
			},
			{
				key: 'psa_integration_id',
				title: 'PSA',
				render: ({ row }) => prettyText(row.psa_integration_id)
			},
			{
				key: 'psa_company_id',
				title: 'PSA ID',
				hideable: true,
				sortable: true
			}
		]}
	/>
</div>
