// web/src/app/(secure)/(admin)/roles/page.tsx
"use client";

import { DataTable } from "@/components/DataTable/DataTable";
import fetchTableData from "@/lib/supabase/table-fetcher";
import {
  DataTableColumn,
  DataTableAction,
  DataTableFetchParams,
} from "@/lib/types/datatable";
import { Eye, Edit, Trash2 } from "lucide-react";
import { Tables } from "@workspace/shared/types/database";

type Data = Tables<"roles">;

const columns: DataTableColumn<Data>[] = [
  {
    key: "name",
    label: "Name",
    sortable: true,
    filterable: true,
    render: (value) => <div className="font-medium">{value}</div>,
  },
  {
    key: "description",
    label: "Description",
    sortable: true,
    filterable: true,
    filterType: "text",
  },
  {
    key: "created_at",
    label: "Created",
    sortable: true,
    render: (value) => new Date(value).toLocaleDateString(),
    exportTransform: (value) => new Date(value).toISOString(),
  },
];

const actions: DataTableAction<Data>[] = [
  {
    id: "view",
    label: "View Details",
    icon: <Eye className="h-4 w-4" />,
    onClick: async (rows) => {
      console.log("Viewing:", rows);
    },
  },
  {
    id: "edit",
    label: "Edit",
    icon: <Edit className="h-4 w-4" />,
    onClick: async (rows) => {
      console.log("Editing:", rows);
    },
  },
  {
    id: "delete",
    label: "Delete",
    icon: <Trash2 className="h-4 w-4" />,
    variant: "destructive",
    disabled: (rows) => rows.some((r) => !r.tenant_id),
    onClick: async (rows) => {
      console.log("Deleting:", rows);
    },
  },
];

export default function Roles() {
  const fetcher = async (params: DataTableFetchParams) => {
    return await fetchTableData("roles", {
      pagination: params,
    });
  };

  return (
    <div className="grid gap-2">
      <div>
        <h1 className="text-2xl font-semibold">Roles</h1>
      </div>
      <DataTable
        columns={columns}
        fetcher={fetcher}
        actions={actions}
        enableSelection={true}
        enableRefresh={true}
        enableExport={true}
        enableColumnToggle={true}
        useUrlState={true}
        urlStateKey="roles"
      />
    </div>
  );
}

// apps/web/src/routes/(private)/roles/+page.svelte
<script lang="ts">
	import DataTable from '$lib/components/table/DataTable.svelte';
	import { createClient } from '$lib/database/client.js';
	import { ORM } from '$lib/database/orm.js';
</script>

<div class="flex size-full flex-col gap-4">
	<h1 class="text-2xl">Roles</h1>

	<DataTable
		fetcher={async (state) => {
			const supabase = createClient();
			const orm = new ORM(supabase);

			const { data } = await orm.getRows('roles', {
				pagination: state
			});

			return (
				data || {
					rows: [],
					total: 0
				}
			);
		}}
		columns={[
			{
				key: 'name',
				title: 'Name',
				searchable: true
			},
			{
				key: 'description',
				title: 'Description',
				searchable: true
			},
			{
				key: 'tenant_id',
				title: 'Pre-Defined',
				render: ({ row }) => (row.tenant_id ? 'Custom' : 'System')
			},
			{
				key: 'created_at',
				title: 'Created At',
				render: ({ row }) => new Date(row.created_at).toDateString(),
				hideable: true
			}
		]}
	/>
</div>
