// apps/web-svelte/src/lib/components/SearchBar.svelte
<script lang="ts">
	import Input from '$lib/components/ui/input/input.svelte';
	import { cn, type WithElementRef } from '$lib/utils.js';
	import type { ComponentType } from 'svelte';
	import type { HTMLInputTypeAttribute, HTMLInputAttributes } from 'svelte/elements';

	type InputType = Exclude<HTMLInputTypeAttribute, 'file'>;

	type Props = {
		onSearch?: (val: string) => void;
		delay?: number;
		icon?: ComponentType;
	} & WithElementRef<
		Omit<HTMLInputAttributes, 'type'> &
			({ type: 'file'; files?: FileList } | { type?: InputType; files?: undefined })
	>;

	const { icon, delay = 300, onSearch, class: classValue, ...rest }: Props = $props();

	let value = $state('');
	let timeout: ReturnType<typeof setTimeout> | null = null;

	function handleInput(e: Event) {
		value = (e.target as HTMLInputElement).value;

		if (timeout) clearTimeout(timeout);
		timeout = setTimeout(() => {
			onSearch?.(value);
		}, delay);
	}
</script>

<div class="relative flex w-full items-center">
	{#if icon}
		<!-- svelte-ignore svelte_component_deprecated -->
		<svelte:component this={icon} class="absolute left-3 w-4" />
	{/if}
	<Input
		{...rest}
		{value}
		oninput={handleInput}
		class={cn(classValue, '!bg-input', icon && 'pl-10')}
	/>
</div>

// web/src/components/SearchBar.tsx
"use client";

import { Input } from "@/components/ui/input";
import { useDebouncedValue } from "@/lib/hooks/useDebouncedValue";
import { cn } from "@/lib/utils";
import { useEffect, useState } from "react";

type Props = {
  delay?: number;
  onSearch?: (query: string) => void;
  lead?: React.ReactNode;
  placeholder?: string;
} & React.ComponentProps<typeof Input>;

export default function SearchBar({
  delay = 0,
  onSearch,
  lead,
  placeholder,
  className,
  ...props
}: Props) {
  const [query, setQuery] = useState("");
  const debouncedQuery = useDebouncedValue(query, delay);

  useEffect(() => {
    onSearch?.(debouncedQuery);
  }, [debouncedQuery]);

  if (lead) {
    return (
      <div className={cn("relative flex items-center w-full", className)}>
        <div className="absolute left-3 z-10 flex items-center text-sm text-muted-foreground font-medium">
          {lead}
        </div>
        <Input
          type="search"
          placeholder={placeholder || "Search..."}
          className={cn("pl-10")} // Adjust padding based on your lead content
          onChange={(e) => setQuery(e.target.value)}
          {...props}
        />
      </div>
    );
  }

  return (
    <Input
      type="search"
      placeholder={placeholder || "Search..."}
      className={className}
      onChange={(e) => setQuery(e.target.value)}
      {...props}
    />
  );
}
