// apps/web/src/lib/components/SearchBox.svelte
<script lang="ts">
	import SearchBar from '$lib/components/SearchBar.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import ScrollArea from '$lib/components/ui/scroll-area/scroll-area.svelte';
	import { cn } from '$lib/utils.js';
	import type { WithElementRef } from 'bits-ui';
	import type { ComponentType } from 'svelte';
	import type { HTMLInputTypeAttribute, HTMLInputAttributes } from 'svelte/elements';

	type InputType = Exclude<HTMLInputTypeAttribute, 'file'>;
	type Option = { label: string; value: string };

	type Props = {
		options: Option[];
		onSelect?: (val: string) => void;
		onSearch?: (val: string) => void;
		delay?: number;
		icon?: ComponentType;
	} & WithElementRef<
		Omit<HTMLInputAttributes, 'type'> &
			({ type: 'file'; files?: FileList } | { type?: InputType; files?: undefined })
	>;

	const {
		options,
		onSelect,
		onSearch,
		placeholder,
		defaultValue,
		class: classValue,
		...rest
	}: Props = $props();

	let selected = $state('');
	let search = $state('');
	let open = $state(false);
	let triggerWidth = $state(0);
	let triggerElement: HTMLDivElement | undefined = $state();

	const handleSearch = (val: string) => {
		onSearch?.(val);
		search = val;
	};

	const handleSelect = (val: string) => {
		onSelect?.(val);
		selected = val;

		open = false;
		search = '';
	};

	const filteredOptions = () => {
		if (!options.length) return [];

		const filtered = options.filter(({ label }) =>
			label.toLowerCase().includes(search.toLowerCase())
		);

		return filtered;
	};

	$effect(() => {
		if (triggerElement && open) {
			triggerWidth = triggerElement.offsetWidth;
		}
	});
</script>

<Popover.Root bind:open>
	<Popover.Trigger>
		<SearchBar
			placeholder={options.find((opt) => opt.value === selected || opt.value === defaultValue)
				?.label || placeholder}
			onSearch={handleSearch}
			class={classValue}
			bind:value={search}
			bind:element={triggerElement}
			{...rest}
		/>
	</Popover.Trigger>
	<Popover.Content
		class={cn('p-1')}
		style={{ width: `!${triggerWidth}px` }}
		onOpenAutoFocus={(e) => e.preventDefault()}
	>
		<ScrollArea class="max-h-96 overflow-auto" style={{ width: `${triggerWidth}px` }} type="always">
			<div>
				{#if !options.length}
					<div>No options available</div>
				{:else if !filteredOptions().length}
					<div>No options found, update search.</div>
				{:else}
					{#each filteredOptions() as option}
						<Button
							variant="ghost"
							class="w-full justify-start"
							onclick={() => handleSelect(option.value)}
						>
							{option.label}
						</Button>
					{/each}
				{/if}
			</div>
		</ScrollArea>
	</Popover.Content>
</Popover.Root>

// web/src/components/SearchBox.tsx
"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import SearchBar from "@/components/SearchBar";

type Option = { label: string; value: string };

type Props = {
  options: Option[];
  placeholder?: string;
  defaultValue?: string;
  lead?: React.ReactNode;
  loading?: boolean;
  delay?: number;
  onSelect?: (value: string) => void;
  onSearch?: (search: string) => void;
};

export default function SearchBox({
  options,
  defaultValue,
  placeholder,
  lead,
  loading,
  delay = 0,
  onSelect,
  onSearch,
}: Props) {
  const [selected, setSelected] = useState(defaultValue);
  const [search, setSearch] = useState("");
  const [isOpen, setIsOpen] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setSelected(defaultValue);
  }, [defaultValue]);

  useEffect(() => {
    if (inputRef.current) inputRef.current.value = "";
    if (!isOpen) {
      setTimeout(() => {
        setSearch("");
      }, 500);
    }
  }, [isOpen]);

  const handleSelect = (option: Option) => {
    setIsOpen(false);
    setSelected(option.value);
    onSelect?.(option.value);
  };

  const handleSearch = useCallback(
    (value: string) => {
      if (onSearch) onSearch(value);
      setSearch(value.toLowerCase());
    },
    [onSearch]
  );

  const filteredOptions = options.filter((o) =>
    o.label.toLowerCase().includes(search)
  );

  return (
    <Popover open={isOpen} onOpenChange={setIsOpen} modal={true}>
      <PopoverTrigger asChild>
        <div className="w-full">
          <SearchBar
            placeholder={
              (selected &&
                options.find((opt) => opt.value === selected)?.label) ||
              placeholder ||
              "Search..."
            }
            onSearch={handleSearch}
            className={cn(lead && "rounded-l-none")}
            delay={delay}
            lead={lead}
            defaultValue={defaultValue}
            ref={inputRef}
          />
        </div>
      </PopoverTrigger>
      <PopoverContent
        align="start" // ensures alignment to the left
        className="flex relative w-[--radix-popover-trigger-width] p-0 z-[1000]"
        style={{ width: "var(--radix-popover-trigger-width)" }}
        onOpenAutoFocus={(e) => e.preventDefault()}
      >
        <ScrollArea className="w-full max-h-96" type="always">
          {loading ? (
            <Button disabled variant="ghost" className="w-full">
              Loading...
            </Button>
          ) : (
            <div className="grid w-full">
              {filteredOptions.map((opt) => (
                <Button
                  key={opt.value}
                  variant="ghost"
                  className="w-full justify-start"
                  onClick={() => handleSelect(opt)}
                >
                  {opt.label}
                </Button>
              ))}
            </div>
          )}
        </ScrollArea>
      </PopoverContent>
    </Popover>
  );
}
